# Generated by Django 6.0.1 on 2026-01-25 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_bird_animal_type_cat_fur_color_alter_animal_breed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_bowls', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='WaterWeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_type', models.CharField(choices=[('reading', 'Leitura de Consumo'), ('refill', 'Troca / Abastecimento')], default='reading', max_length=10)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bowl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='monitoring.waterbowl')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
    ]
