# Generated by Django 6.0.1 on 2026-03-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbowl',
            name='is_reference',
            field=models.BooleanField(default=False, help_text='Indica se este pote é usado como referência (evaporação) e não para consumo do animal.'),
        ),
    ]
