# Generated by Django 6.0.1 on 2026-03-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_waterbowl_is_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterweightlog',
            name='observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
