# Generated by Django 6.0.1 on 2026-03-13 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_bird_animal_type_cat_fur_color_alter_animal_breed_and_more'),
        ('monitoring', '0003_alter_waterweightlog_observed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodWeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_type', models.CharField(choices=[('reading', 'Leitura de Consumo'), ('refill', 'Troca / Abastecimento')], default='reading', max_length=10)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_weight_logs', to='animals.animal')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
    ]
