# Generated by Django 6.0.1 on 2026-03-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_foodbrand_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodweightlog',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_weight_logs', to='monitoring.foodbrand'),
        ),
        migrations.AddField(
            model_name='foodweightlog',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_weight_logs', to='monitoring.foodtype'),
        ),
    ]
