# Generated by Django 6.0.1 on 2026-03-13 17:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_foodweightlog_brand_foodweightlog_type'),
        ('animals', '0002_bird_animal_type_cat_fur_color_alter_animal_breed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('observed_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='animals.animal')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
    ]

