# Generated by Django 6.0.1 on 2026-03-13 17:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_bird_animal_type_cat_fur_color_alter_animal_breed_and_more'),
        ('monitoring', '0007_animaldiaryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('identified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='animals.animal')),
            ],
            options={
                'ordering': ['-identified_at'],
            },
        ),
    ]

