# Generated by Django 6.0.1 on 2026-03-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_animalexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalexam',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='exams/'),
        ),
        migrations.AddField(
            model_name='animalexam',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]

