# Generated by Django 6.0.1 on 2026-03-14 01:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_bird_animal_type_cat_fur_color_alter_animal_breed_and_more'),
        ('monitoring', '0009_animalexam_file_animalexam_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_exams', to='animals.animal')),
                ('exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_exams', to='monitoring.examtype')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_exams', to='monitoring.animalexam')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamParameterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_value', models.CharField(max_length=120)),
                ('reference_range', models.CharField(blank=True, max_length=120, null=True)),
                ('raw_parameter_name', models.CharField(blank=True, max_length=120, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_results', to='monitoring.extractedexam')),
                ('parameter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.parametertype')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='monitoring.measurementunit')),
            ],
            options={
                'ordering': ['parameter_type__name'],
                'unique_together': {('exam', 'parameter_type')},
            },
        ),
        migrations.AddField(
            model_name='extractedexam',
            name='parameters',
            field=models.ManyToManyField(related_name='extracted_exams', through='monitoring.ExamParameterResult', to='monitoring.parametertype'),
        ),
    ]

