# Generated by Django 6.0.1 on 2026-03-14 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_examtype_extractedexam_measurementunit_parametertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedexam',
            name='observations',
            field=models.TextField(blank=True, help_text='Impressão diagnóstica, conclusão ou observações gerais do exame (ex.: IMPRESSÃO DIAGNÓSTICA de ultrassom).', null=True),
        ),
        migrations.CreateModel(
            name='ExamOrganFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_name', models.CharField(help_text='Nome do órgão ou estrutura (ex.: Rins, Vesícula urinária).', max_length=200)),
                ('description', models.TextField(help_text='Descrição/achado para esse órgão.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ_findings', to='monitoring.extractedexam')),
            ],
            options={
                'ordering': ['order', 'organ_name'],
            },
        ),
    ]
