# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_extractedexam_observations_examorganfinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedexam',
            name='gemini_prompt_tokens',
            field=models.PositiveIntegerField(blank=True, help_text='Tokens de prompt consumidos na extração com Gemini.', null=True),
        ),
        migrations.AddField(
            model_name='extractedexam',
            name='gemini_completion_tokens',
            field=models.PositiveIntegerField(blank=True, help_text='Tokens de resposta (completion) consumidos na extração com Gemini.', null=True),
        ),
        migrations.AddField(
            model_name='extractedexam',
            name='gemini_total_tokens',
            field=models.PositiveIntegerField(blank=True, help_text='Total de tokens consumidos na extração com Gemini.', null=True),
        ),
    ]
