# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_extractedexam_gemini_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalexam',
            name='source_exam_type_label',
            field=models.CharField(
                blank=True,
                help_text='Texto do tipo de exame extraído da página do SimplesPet (ex.: Ultrassonografia, Hemograma + Bioquímico).',
                max_length=200,
                null=True,
            ),
        ),
    ]
