# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_animalexam_source_exam_type_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalexam',
            name='source_observed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Data/hora do exame extraída da página do SimplesPet (fallback quando a IA não encontrar no documento).',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='extractedexam',
            name='observed_at_found_in_document',
            field=models.BooleanField(
                blank=True,
                help_text='True se a IA encontrou data/hora de realização/coleta no documento; False se usou sugestão da página.',
                null=True,
            ),
        ),
    ]
