# Generated by Django 6.0.1

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('monitoring', '0014_animalexam_source_observed_at_extractedexam_observed_at_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Remédio',
                'verbose_name_plural': 'Remédios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da receita.')),
                ('source_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='receitas/')),
                ('identified_at', models.DateTimeField(default=timezone.now)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='animals.animal')),
            ],
            options={
                'ordering': ['-data', '-identified_at'],
                'verbose_name_plural': 'Receitas',
            },
        ),
        migrations.CreateModel(
            name='IndicacaoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_apresentacao', models.CharField(blank=True, help_text='Forma de apresentação (ex.: frasco, comprimido).', max_length=100, null=True)),
                ('medida_apresentacao', models.CharField(blank=True, help_text='Medida da apresentação (ex.: 2mg/ml).', max_length=80, null=True)),
                ('dosagem', models.CharField(blank=True, help_text='Dosagem (ex.: 0,4ml).', max_length=80, null=True)),
                ('frequencia', models.CharField(blank=True, help_text='Frequência (ex.: a cada 12 horas).', max_length=120, null=True)),
                ('periodo', models.CharField(blank=True, help_text='Período (ex.: por 7 dias).', max_length=120, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicacoes', to='monitoring.receita')),
                ('remedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicacoes', to='monitoring.remedio')),
            ],
            options={
                'ordering': ['order', 'remedio__name'],
                'verbose_name': 'Indicação de medicamento',
                'verbose_name_plural': 'Indicações de medicamento',
            },
        ),
    ]
