# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_remedio_receita_indicacaomedicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedio',
            name='principio_ativo',
            field=models.CharField(
                blank=True,
                help_text='Nome do princípio ativo ou substância.',
                max_length=200,
                null=True,
            ),
        ),
    ]
