# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_remedio_principio_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='source_identifier',
            field=models.CharField(
                blank=True,
                help_text='Identificador único da receita na origem (ex.: id do evento no SimplesPet).',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
