# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_receita_source_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='gemini_prompt_tokens',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Tokens de prompt consumidos no processamento com Gemini.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='receita',
            name='gemini_completion_tokens',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Tokens de resposta (completion) consumidos no processamento com Gemini.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='receita',
            name='gemini_total_tokens',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Total de tokens consumidos no processamento com Gemini.',
                null=True,
            ),
        ),
    ]
