# Generated by Django 6.0.1 on 2026-03-19 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_bird_animal_type_cat_fur_color_alter_animal_breed_and_more'),
        ('monitoring', '0018_receita_gemini_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFoodConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_consumption', models.DecimalField(decimal_places=2, help_text='Consumo total de ração no dia (soma líquida considerando refills).', max_digits=10)),
                ('negative_periods', models.PositiveIntegerField(default=0, help_text='Quantidade de períodos em que o consumo bruto calculado ficou negativo (possível refill não marcado).')),
                ('missing_readings', models.BooleanField(default=False, help_text='True se foram detectadas faltas de leitura de ração em períodos relevantes no dia.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_food_consumptions', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Consumo diário de ração',
                'verbose_name_plural': 'Consumos diários de ração',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('animal', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyWaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gross_consumption', models.DecimalField(decimal_places=2, help_text='Soma do consumo bruto de água em todos os potes de consumo no dia.', max_digits=10)),
                ('evaporation', models.DecimalField(decimal_places=2, help_text='Evaporação estimada a partir do pote de referência no dia.', max_digits=10)),
                ('net_consumption', models.DecimalField(decimal_places=2, help_text='Consumo líquido (gross_consumption - evaporation), truncado em zero quando negativo.', max_digits=10)),
                ('negative_periods', models.PositiveIntegerField(default=0, help_text='Quantidade de períodos em que o consumo bruto calculado ficou negativo (possível refill não marcado).')),
                ('missing_readings', models.BooleanField(default=False, help_text='True se foram detectadas faltas de leitura para algum pote em períodos relevantes no dia.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_water_consumptions', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Consumo diário de água',
                'verbose_name_plural': 'Consumos diários de água',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('animal', 'date')},
            },
        ),
    ]
