# Generated by Django 6.0.1 on 2026-01-24 03:24

import django.utils.timezone
import pgcrypto.fields
from django.db import migrations, models
from django.contrib.postgres.operations import CryptoExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        CryptoExtension(),

        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this user has all permissions without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email',
                 pgcrypto.fields.EncryptedEmailField(charset='utf-8', check_armor=True, cipher='aes', unique=True,
                                                     versioned=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('first_name',
                 pgcrypto.fields.EncryptedTextField(blank=True, charset='utf-8', check_armor=True, cipher='aes',
                                                    max_length=30, versioned=False)),
                ('last_name',
                 pgcrypto.fields.EncryptedTextField(blank=True, charset='utf-8', check_armor=True, cipher='aes',
                                                    max_length=30, versioned=False)),
                ('groups', models.ManyToManyField(blank=True,
                                                  help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                                  related_name='user_set', related_query_name='user', to='auth.group',
                                                  verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                                                            related_name='user_set', related_query_name='user',
                                                            to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]