# Generated by Django 6.0.1 on 2026-01-25 02:24

import pgcrypto.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='first_name',
            field=pgcrypto.fields.EncryptedCharField(blank=True, charset='utf-8', check_armor=True, cipher='aes', versioned=False),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='last_name',
            field=pgcrypto.fields.EncryptedCharField(blank=True, charset='utf-8', check_armor=True, cipher='aes', versioned=False),
        ),
    ]
