# Generated by Django 6.0.1 on 2026-01-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.animal')),
                ('feather_color', models.CharField(blank=True, choices=[('white', 'Branco'), ('black', 'Preto')], max_length=100, null=True)),
            ],
            bases=('animals.animal',),
        ),
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.CharField(blank=True, choices=[('cat', 'Gato'), ('bird', 'Pássaro')], default='cat', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='fur_color',
            field=models.CharField(blank=True, choices=[('white', 'Branco'), ('black', 'Preto')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='specie',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
